# -*- coding: utf-8 -*-
"""从 en/music-services.md 生成 de/music-services.md：以英文版为底本，$→€ 平价，文字译成德语书面体。"""
import io, os, sys

BASE = os.path.dirname(os.path.abspath(__file__))
src = io.open(os.path.join(BASE, '..', '..', 'content', 'en', 'music-services.md'), encoding='utf-8').read()

R = [
    ('description: "Professional music production services, including mixing and mastering"',
     'description: "Professionelle Dienstleistungen rund um Musikproduktion, Mixing und Mastering"'),
    ('<p>Professional Music Production Services</p>', '<p>Professionelle Musikproduktions-Services</p>'),
    ('<p>Mastering \u00b7 Music Production \u00b7 Commercial Work</p>',
     '<p>Mastering \u00b7 Musikproduktion \u00b7 Kommerzielle Zusammenarbeit</p>'),
    ('<h3>Mastering Service</h3>', '<h3>Mastering-Service</h3>'),
    ('<div class="product-description">Professional mastering that brings your music up to commercial standards, with musicality intact</div>',
     '<div class="product-description">Professionelles Mastering, das Ihre Musik auf kommerzielles Niveau hebt \u2014 bei unversehrter Musikalität</div>'),
    ('<div class="level-name">Standard Mastering</div>', '<div class="level-name">Standard-Mastering</div>'),
    ('<div class="level-price">$45/track</div>', '<div class="level-price">45 \u20ac/Track</div>'),
    ('<div class="level-desc">Label-grade standard, for finished mixes</div>',
     '<div class="level-desc">Label-Standard, für fertige Mixe</div>'),
    ('<div class="level-name">Premium Mastering</div>', '<div class="level-name">Premium-Mastering</div>'),
    ('<div class="level-price">$135/track</div>', '<div class="level-price">135 \u20ac/Track</div>'),
    ('<div class="level-desc">Stem mixing + mastering, handled with professional methods</div>',
     '<div class="level-desc">Stem-Mixing + Mastering, professionelle Methodik</div>'),
    ('<div class="notice-text">For premium mixing &amp; mastering, the client is responsible for the quality of the source material and the mix foundation. Pre-existing issues \u2014 stem resolution, level distortion, excessive coloration, timing errors \u2014 remain the client\u2019s responsibility if left uncorrected after discussion.</div>',
     '<div class="notice-text">Beim Premium-Mixing &amp; -Mastering liegt die Verantwortung für die Qualität des Quellmaterials und der Mix-Basis beim Auftraggeber. Vorbestehende Probleme \u2014 Stem-Auflösung, Pegelverzerrung, übermäßige Coloration, Timing-Fehler \u2014 bleiben bei unzureichender Korrektur nach Absprache in der Verantwortung des Auftraggebers.</div>'),
    ('<div class="price-tag">from $45</div>', '<div class="price-tag">ab 45 \u20ac</div>'),
    ('<h3>Full Track Production</h3>', '<h3>Komplette Track-Produktion</h3>'),
    ('<div class="product-description">Built from the ground up \u2014 turning your ideas into professional tracks</div>',
     '<div class="product-description">Von Grund auf neu erschaffen \u2014 Ihre Ideen werden zu professionellen Tracks</div>'),
    ('<div class="detail-text">Hand over your ideas, sketches and presets</div>',
     '<div class="detail-text">Übergeben Sie Ihre Ideen, Skizzen und Presets</div>'),
    ('<div class="detail-text">Deep collaboration throughout the process</div>',
     '<div class="detail-text">Tiefe Zusammenarbeit während des gesamten Prozesses</div>'),
    ('<div class="detail-text">Release-ready tracks, finished to a high standard</div>',
     '<div class="detail-text">Releasefertige Tracks in hoher Qualität</div>'),
    ('<div class="price-tag">$750</div>', '<div class="price-tag">750 \u20ac</div>'),
    ('<a href="../contact/index.html" class="buy-button left">Inquire</a>',
     '<a href="../contact/index.html" class="buy-button left">Anfragen</a>'),
    ('<a href="#" class="buy-button right" onclick="openMasteringModal()">Learn More</a>',
     '<a href="#" class="buy-button right" onclick="openMasteringModal()">Details</a>'),
    ('<a href="#" class="buy-button right" onclick="openServiceModal()">Learn More</a>',
     '<a href="#" class="buy-button right" onclick="openServiceModal()">Details</a>'),
    ('<h2>How It Works</h2>', '<h2>So funktioniert es</h2>'),
    ('<h3>Track Review</h3>', '<h3>Track-Prüfung</h3>'),
    ('<p>Submit a demo \u2014 we assess the track and match it to the right service</p>',
     '<p>Reichen Sie ein Demo ein \u2014 wir bewerten den Track und empfehlen den passenden Service</p>'),
    ('<h3>Tailored Plan</h3>', '<h3>Individuelles Konzept</h3>'),
    ('<p>A personalized plan and quote, built around your goals</p>',
     '<p>Ein persönlicher Plan und ein Angebot, abgestimmt auf Ihre Ziele</p>'),
    ('<h3>Deep Collaboration</h3>', '<h3>Enge Zusammenarbeit</h3>'),
    ('<p>Close communication at every stage, so the result matches your vision</p>',
     '<p>Enge Absprache in jeder Phase, damit das Ergebnis Ihrer Vision entspricht</p>'),
    ('<h3>Delivery &amp; Release</h3>', '<h3>Lieferung &amp; Release</h3>'),
    ('<p>High-quality final delivery, with support for release and promotion</p>',
     '<p>Hochwertige Endabnahme, mit Unterstützung bei Release und Promotion</p>'),
    ('<h2>Eonun Track Production Service</h2>', '<h2>Eonun Track-Produktionsservice</h2>'),
    ('<p>With years of focus on Uplifting Trance production, I turn your specific requirements into finished tracks with mature structure, precise sound design and international release standards. Whether it\u2019s developing a rough idea, deepening a half-finished track, or building a complete single from scratch, a disciplined production process makes your musical ideas real \u2014 release-ready, shareable and distinctive.</p>',
     '<p>Mit jahrelanger Fokussierung auf Uplifting-Trance-Produktion verwandle ich Ihre konkreten Anforderungen in fertige Tracks mit ausgereifter Struktur, präzisem Sounddesign und internationalen Release-Standards. Ob die Weiterentwicklung einer groben Idee, die Vertiefung eines halbfertigen Tracks oder der komplette Neubau einer Single \u2014 ein disziplinierter Produktionsprozess macht Ihre musikalischen Ideen real: releasefertig, teilbar und unverwechselbar.</p>'),
    ('<h3>What\u2019s Included</h3>', '<h3>Leistungsumfang</h3>'),
    ('<li>A complete production \u2014 arrangement, sound design, mixing and structure optimization \u2014 built from your melody, reference tracks, MIDI files or creative direction; suitable for commercial use in games, film and more.</li>',
     '<li>Eine komplette Produktion \u2014 Arrangement, Sounddesign, Mixing und Strukturoptimierung \u2014 auf Basis Ihrer Melodie, Referenztracks, MIDI-Dateien oder kreativen Vorgabe; geeignet für die kommerzielle Nutzung in Games, Film und mehr.</li>'),
    ('<li>Two rounds of free revisions, so the final track matches your style and expectations.</li>',
     '<li>Zwei kostenlose Überarbeitungsrunden, damit der fertige Track zu Ihrem Stil und Ihren Erwartungen passt.</li>'),
    ('<li>Standard turnaround is 14 calendar days; an express option delivers within 7 days.</li>',
     '<li>Die Standard-Lieferzeit beträgt 14 Kalendertage; per Express ist die Lieferung innerhalb von 7 Tagen möglich.</li>'),
    ('<h3>Why This Service</h3>', '<h3>Warum dieser Service</h3>'),
    ('<p>As a producer featured in an exclusive interview by RIIR, an international modern Trance label, my work is built on the modern Uplifting Trance production system \u2014 I keep up with current aesthetic standards while keeping a broad view of the genre, and every track is polished to the release standards of international labels. I don\u2019t play insider games and I don\u2019t gatekeep: the quality of the work is the only filter, so your music can hold its own in a global market.</p>',
     '<p>Als Produzent, dem RIIR, einem internationalen modernen Trance-Label, ein exklusives Interview widmete, basiert meine Arbeit auf dem modernen Uplifting-Trance-Produktionssystem \u2014 ich halte mich an aktuelle ästhetische Standards und behalte gleichzeitig den ganzen Genre-Kontext im Blick; jeder Track wird nach den Release-Standards internationaler Labels ausgearbeitet. Ich mache keine Insider-Spiele und kenne kein Gatekeeping: Die Qualität der Arbeit ist das einzige Kriterium, damit Ihre Musik auf dem Weltmarkt bestehen kann.</p>'),
    ('<h3>What You\u2019ll Provide</h3>', '<h3>Benötigtes Material</h3>'),
    ('<li>Within 24 hours of placing the order, please provide project materials: video clips, story references, mood guidelines, reference music or a style description.</li>',
     '<li>Bitte reichen Sie innerhalb von 24 Stunden nach Auftragserteilung das Projektmaterial ein: Videosequenzen, Story-Referenzen, Stimmungsvorgaben, Referenzmusik oder eine Stilbeschreibung.</li>'),
    ('<li>Please also specify: the style (Uplifting Trance only for this service), the length of each piece, the overall mood, and the intended use or scene.</li>',
     '<li>Bitte geben Sie außerdem an: Stil (für diesen Service ausschließlich Uplifting Trance), Länge des jeweiligen Stücks, Gesamtstimmung und vorgesehene Verwendung bzw. Einsatzszenario.</li>'),
    ('<h3>Important Notes &amp; Copyright Terms</h3>', '<h3>Wichtige Hinweise &amp; Urheberrechtsbedingungen</h3>'),
    ('<li>As the producer, I retain 10% of copyright revenue (including composition credit, mechanical rights and sync rights). This share does not affect your project\u2019s worldwide distribution, screening, or revenue across all channels.</li>',
     '<li>Als Produzent behalte ich 10 % der Urheberrechtserträge (einschließlich Kompositionsnennung, mechanischer Rechte und Synchronisationsrechte). Dieser Anteil berührt nicht die weltweite Verbreitung, Vorführung oder die Einnahmen Ihres Projekts über alle Kanäle.</li>'),
    ('<li>After delivery, additional revisions requested due to project changes are billed at $100 per hour.</li>',
     '<li>Nach Lieferung werden zusätzliche, auf Projektänderungen zurückzuführende Überarbeitungen mit 100 \u20ac pro Stunde berechnet.</li>'),
    ('<li>I guarantee production quality and fit for the intended use throughout, but I do not promise or guarantee that a work will meet any particular third party\u2019s acceptance criteria.</li>',
     '<li>Ich garantiere während des gesamten Prozesses Produktionsqualität und Eignung für den vorgesehenen Zweck, verspreche oder garantiere jedoch nicht, dass ein Werk die Akzeptanzkriterien eines bestimmten Dritten erfüllt.</li>'),
    ('<h3>Pricing</h3>', '<h3>Preise</h3>'),
    ('<span class="price-label">Standard production (14-day delivery):</span>',
     '<span class="price-label">Standardproduktion (Lieferung in 14 Tagen):</span>'),
    ('<span class="price-value">$750</span>', '<span class="price-value">750 \u20ac</span>'),
    ('<span class="price-label">Express production (7-day delivery):</span>',
     '<span class="price-label">Expressproduktion (Lieferung in 7 Tagen):</span>'),
    ('<span class="price-value">$950</span>', '<span class="price-value">950 \u20ac</span>'),
    ('<h3>Common Questions</h3>', '<h3>Häufige Fragen</h3>'),
    ('<li>Materials: detailed specs are shared after ordering \u2014 happy to confirm details in advance</li>',
     '<li>Material: Detaillierte Spezifikationen erhalten Sie nach Bestellung \u2014 gern klären wir Details vorab</li>'),
    ('<li>Process: requirements confirmed \u2192 first draft \u2192 revisions \u2192 final delivery</li>',
     '<li>Ablauf: Anforderungen bestätigt \u2192 erster Entwurf \u2192 Überarbeitungen \u2192 Endabnahme</li>'),
    ('<li>Turnaround: 14 calendar days standard, express within 7 days</li>',
     '<li>Lieferzeit: 14 Kalendertage im Standard, Express innerhalb von 7 Tagen</li>'),
    ('<h3>Start Your Custom Project</h3>', '<h3>Starten Sie Ihr Custom-Projekt</h3>'),
    ('<p>Whether you need a single mood-setting piece or a full custom score for a complete project, I work to a stable, commercially usable standard \u2014 turning scene emotion into Uplifting Trance that truly fits. Send over your project materials, and let\u2019s make music that fits the scene, lands the emotion, and holds a professional standard.</p>',
     '<p>Ob Sie nur ein einzelnes Stimmungsstück oder eine komplette individuelle Vertonung für ein ganzes Projekt benötigen \u2014 ich arbeite nach stabilen, kommerziell nutzbaren Standards und verwandle Szenenstimmung in Uplifting Trance, die wirklich passt. Senden Sie Ihr Projektmaterial, und lassen Sie uns Musik erschaffen, die zur Szene passt, die Emotion trifft und professionelles Niveau hält.</p>'),
    ('<a href="../contact/index.html" class="modal-cta-button">Start a Project</a>',
     '<a href="../contact/index.html" class="modal-cta-button">Projekt starten</a>'),
    ('<h2>Eonun Mixing &amp; Mastering Service</h2>', '<h2>Eonun Mixing- &amp; Mastering-Service</h2>'),
    ('<p>Working with the aesthetic logic of Trance and the specs of digital distribution: dynamics, frequency balance and loudness \u2014 so the music feels right and plays right on every platform.</p>',
     '<p>Nach der ästhetischen Logik des Trance und den Spezifikationen digitaler Distribution: Dynamik, Frequenzbalance und Lautheit \u2014 damit die Musik sich richtig anfühlt und auf jeder Plattform richtig klingt.</p>'),
    ('<h3>Service Tiers</h3>', '<h3>Leistungsstufen</h3>'),
    ('<h4>Standard Mastering Tune-Up \u2014 $45</h4>', '<h4>Standard-Mastering-Kalibrierung \u2014 45 \u20ac</h4>'),
    ('<p>Starting from your final stereo mix: loudness calibration, global frequency cleanup and playback optimization, delivered as a master that meets streaming release specs.</p>',
     '<p>Ausgehend von Ihrem fertigen Stereomix: Lautheitskalibrierung, globale Frequenzbereinigung und Wiedergabeoptimierung \u2014 geliefert als Master, der den Streaming-Release-Spezifikationen entspricht.</p>'),
    ('<h4>Full-Cycle Mixing + Mastering \u2014 $135</h4>', '<h4>Komplettes Mixing + Mastering \u2014 135 \u20ac</h4>'),
    ('<p>Detailed mixing of up to 10 grouped stems \u2014 low-end structure, melodic layers, drum cohesion and spatial design \u2014 followed by targeted mastering for dynamics and loudness. Delivered release-ready.</p>',
     '<p>Feinmixing von bis zu 10 gruppierten Stems \u2014 Low-End-Struktur, melodische Ebenen, Drum-Kohäsion und räumliches Design \u2014 gefolgt von gezieltem Mastering für Dynamik und Lautheit. Geliefert releasefertig.</p>'),
    ('<h3>Delivery Specs</h3>', '<h3>Material-Spezifikationen</h3>'),
    ('<li><strong>Stereo mastering:</strong> submit your final stereo mix as WAV, 24-bit, at the project\u2019s original sample rate (44.1 / 48 kHz) \u2014 no upsampling or transcoding. Leave -6 dB of headroom (anything between -6 and -3 dBFS is fine); no limiter or bus compression on the master bus.</li>',
     '<li><strong>Stereo-Mastering:</strong> Reichen Sie Ihren fertigen Stereomix als WAV, 24-Bit, in der Original-Samplerate des Projekts (44,1 / 48 kHz) ein \u2014 kein Upsampling, keine Transkodierung. Halten Sie -6 dB Headroom frei (alles zwischen -6 und -3 dBFS ist in Ordnung); kein Limiter und keine Bus-Kompression auf dem Masterbus.</li>'),
    ('<li><strong>Stem mixing:</strong> WAV, 24-bit, same sample rate as the project, up to 10 stems; export reverb, delay and other effect tracks separately; leave about -6 dB of headroom per stem. No clipping.</li>',
     '<li><strong>Stem-Mixing:</strong> WAV, 24-Bit, gleiche Samplerate wie das Projekt, bis zu 10 Stems; Reverb-, Delay- und andere Effektspuren separat exportieren; pro Stem ca. -6 dB Headroom freihalten. Kein Clipping.</li>'),
    ('<li><strong>File delivery:</strong> include the track name and BPM in the file name, and send the archive by email or messaging app \u2014 a cloud drive link works too.</li>',
     '<li><strong>Dateiübergabe:</strong> Vergeben Sie Dateinamen mit Titel und BPM und senden Sie das Archiv per E-Mail oder Messenger \u2014 ein Cloud-Link funktioniert ebenfalls.</li>'),
    ('<h3>Turnaround &amp; Express</h3>', '<h3>Lieferzeit &amp; Express</h3>'),
    ('<li>Standard: 3\u20135 business days</li>', '<li>Standard: 3\u20135 Werktage</li>'),
    ('<li>Express full-cycle delivery within 24 hours: +$29</li>',
     '<li>Komplettes Express-Mixing + Mastering innerhalb von 24 Stunden: +29 \u20ac</li>'),
    ('<h3>The Core of the Quality</h3>', '<h3>Das Qualitätsfundament</h3>'),
    ('<p>Years of focus on Trance bus processing. Every track is adjusted to its own structure and style, and delivered to digital distribution specs.</p>',
     '<p>Jahrelange Fokussierung auf Trance-Busbearbeitung. Jeder Track wird an seine eigene Struktur und seinen eigenen Stil angepasst und nach den Spezifikationen digitaler Distribution geliefert.</p>'),
    ('<h3>Ready for Release</h3>', '<h3>Bereit für den Release</h3>'),
    ('<p>From a quick loudness tune-up to deep mixing work, everything is held to release specs \u2014 delivered ready to publish. If you already have a target label in mind, the master can be tailored to the sonic aesthetic and loudness habits of its catalog, so the finished track sits naturally within that label\u2019s sound.</p>',
     '<p>Von der schnellen Lautheitskalibrierung bis zur tiefgehenden Mixing-Arbeit gilt alles den Release-Spezifikationen \u2014 geliefert veröffentlichungsbereit. Falls Sie bereits ein Ziel-Label im Blick haben, kann das Master gezielt an die Klangästhetik und Lautheitsgewohnheiten dessen Katalogs angepasst werden, damit der fertige Track nahtlos in den Sound des Labels passt.</p>'),
    ("throw new Error('Slogan file failed to load')", "throw new Error('Slogan-Datei konnte nicht geladen werden')"),
    ("console.log('Failed to load slogans, using fallback text:', error)", "console.log('Slogans konnten nicht geladen werden, Fallback-Text wird verwendet:', error)"),
]

for old, new in R:
    n = src.count(old)
    if n == 0:
        print('MISS: ' + old[:70]); sys.exit(1)
    src = src.replace(old, new)

leftover = [l.strip()[:80] for l in src.split('\n') if '$' in l and '${' not in l and not l.strip().startswith(('/*','*','<!--','//'))]
if leftover:
    print('$ leftover:'); [print(' ', x) for x in leftover]; sys.exit(1)

old_slogan = 'Part of a young life, devoted to the art of Trance'
if src.count(old_slogan) != 2:
    print('slogan count != 2: %d' % src.count(old_slogan)); sys.exit(1)
src = src.replace(old_slogan, 'Ein Stück eines jungen Lebens, der Kunst des Trance gewidmet')

out = os.path.join(BASE, '..', '..', 'content', 'de', 'music-services.md')
io.open(out, 'w', encoding='utf-8', newline='\n').write(src)
print('written: ' + out)
